IJN

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -176,6 +176,8 @@ jobs:
            cd backend 
            npm install
            npm audit fix --audit-level=critical --force
+           npm audit fix --force
+           npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
@@ -205,6 +207,7 @@ jobs:
             aws cloudformation \
               list-exports --query "Exports[?Name==\`Backend-Public-IP\`].Value" \
               --no-paginate --output text >> .circleci/ansible/inventory.txt
+            cat ~/project/.circleci/ansible/inventory.txt
             
       - persist_to_workspace:
           root: ~/
@@ -247,6 +250,7 @@ jobs:
       - run:
           name: Configure server
           command: |
+            cat .circleci/ansible/inventory.txt
             cd .circleci/ansible
             export ANSIBLE_HOST_KEY_CHECKING=False
             ansible-playbook -i inventory.txt configure-server.yml
@@ -266,9 +270,8 @@ jobs:
             command: |
               cd backend
               npm install
-              npm run build
               npm run migrations > migrations_dump.txt
-              cat migrations_dump.txt
+              cat ~/project/backend/migrations_dump.txt
          - run:
             name: Send migration status to kvdb.io
             command: |   
@@ -296,6 +299,7 @@ jobs:
                 list-exports --query "Exports[?Name==\`Backend-Public-IP\`].Value" \
                 --no-paginate --output text)
                 echo "API_URL=${API_URL}" >> frontend/.env
+                cat frontend/.env
         - run:
             name: deploy frontend objects
             command: |
@@ -322,13 +326,14 @@ jobs:
         - run:
             name: Install dependencies
             command: |
-              apk add --update ansible 
-              apk add --update nodejs 
-              apk add --update npm 
-              apk add --update tar 
-              apk add --update gzip
-              apk add --update openssh-client git
-              apk add --update tree
+              apk add --update --no-cache ansible 
+              apk add --update --no-cache nodejs 
+              apk add --update --no-cache npm 
+              apk add --update --no-cache tar 
+              apk add --update --no-cache gzip
+              apk add --update --no-cache openssh-client git
+              apk add --update --no-cache tree
+              apk add --update --no-cache rsync
               pip3 install awscli
         - run:
            name: Deploy backend
@@ -348,11 +353,10 @@ jobs:
               npm run build
               cd ..
               tar -C backend -czvf artifact.tar.gz .
-              tree -afC /root/project/.circleci -I *node_modules*
               mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
               mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
               cd .circleci/ansible
-              echo "Contents  of the inventory.txt file is -------"
+              echo "Contents  of the inventory.txt file is -------$(tail -1 inventory.txt)"
               cat inventory.txt
               export ANSIBLE_HOST_KEY_CHECKING=False
               ansible-playbook -i inventory.txt deploy-backend.yml
@@ -380,7 +384,13 @@ jobs:
                 --no-paginate --output text)
              API_URL="http://${BACKEND_IP}:3030"
              echo "${API_URL}/api/status"
-             curl -s"${API_URL}/api/status"
+             sleep 30
+             if curl -s $API_URL/api/status | grep "ok"
+             then
+               exit 0
+             else
+               exit 1
+             fi
              
       - destroy-environment
       - revert-migrations
@@ -402,7 +412,7 @@ jobs:
           name: Smoke test for front end
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"             
-            echo ${URL} 
+            echo ${URL}
             if curl -s ${URL} | grep "Welcome"
             then
               return 0
@@ -424,7 +434,7 @@ jobs:
             OldWorkflowID=$(aws cloudformation \
             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
             --no-paginate --output text)
-            curl https://kvdb.io/X8AvJuBJmaFNQRf6CeZh4c/migration_${CIRCLE_WORKFLOW_ID:0:7} \
+            curl https://kvdb.io/X8AvJuBJmaFNQRf6CeZh4c/oldworkflowid \
             -d "$OldWorkflowID"  
       - run:
           name: Updating cloudfront distribution
@@ -432,7 +442,7 @@ jobs:
             aws cloudformation deploy \
             --template-file .circleci/files/cloudfront.yml \
             --stack-name cloudfront-${CIRCLE_WORKFLOW_ID:0:7} \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
             --tags project=udapeople
   
   add-prometheus-node-exporter:
@@ -484,7 +494,7 @@ jobs:
               --query "StackSummaries[*].StackName" \
               --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
             echo $STACKS
-            if [[ "${CIRCLE_WORKFLOW_ID:0:5}" =~ "${OldWorkflowID}" ]]
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
               aws cloudformation delete-stack --stack-name "starter-frontend-${OldWorkflowID}"
@@ -530,9 +540,9 @@ workflows:
           requires: [deploy-frontend]
       - smoke-test-backend:
           requires: [deploy-backend]
-      - cloudfront-update:
-          requires: [smoke-test-frontend]
-      - add-prometheus-node-exporter:
-          requires: [smoke-test-backend]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cloudfront-update:
+      #     requires: [smoke-test-frontend]
+      # - add-prometheus-node-exporter:
+      #     requires: [smoke-test-backend]
+      # - cleanup:
+      #     requires: [cloudfront-update]
